### ISSUE TITLE
[FR] Adding specific sytle for "Today" date

### ISSUE THREAD

**Issue by Moyf** [karstenpedersen/obsidian-daily-note-navbar#19]
In Calendar Plugin, as you can see, the "Today" is red text and the day you open now is red background.
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/7ea27749-5014-44a7-bee8-f4483348d3ae)

So I'm thinking maybe adding some specific style for "Today" would be more user-friendly?

And I found that you've already added a specific css class for "Today" so it's easy for users to just adding css snippet by themself, which is great!
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/1d8a2451-8d48-499a-b15a-e020134ccc8d)

I have already made the changes myself, this is just a suggestion (so that other users can also benefit) ☺️
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/c77ff3b8-420a-4f26-a549-9b7d9354db00)

```css
/* DailyNote Navbar */
.daily-note-navbar__date.daily-note-navbar__current {
    text-decoration: underline;
}
```

**Comment by karstenpedersen** [comment]
I implemented the css class because another user recommended the same thing. I would like to style it by default, but I have not come up with a good style. I don't like adding underlines, as that signals that it is a link.

I could maybe add ">Wed 26<", adding > and < around todays date. what do you think of this? This could be implemented with CSS so people could override it. I could also make a toggle in the settings tab for it.

**Comment by Moyf** [comment]
Oh, I personally think that adding extra characters would make the apperance less consistent.

Maybe learn from the Calendar?
Accent Color & Bold for Today, and background for Active Day:
![image](https://github.com/karstenpedersen/obsidian-daily-note-navbar/assets/4013062/dc173b28-b6ce-4efa-af90-2877ad8a31d1)

```css
/* DailyNote Navbar */
.daily-note-navbar__date.daily-note-navbar__current {
    font-weight: bold;
    color: var(--color-accent);
}

.daily-note-navbar__date.daily-note-navbar__active:not(.daily-note-navbar__current) {
    color: white;
    background-color: var(--color-accent);
    margin: 5px;
}

```

---

And yeah, I definately agree that it's better for users to be able to choose styles (or setting to None so that they can modify by themselves) ; )
